/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerInfo {
  'name' : string,
  'email' : string,
  'shippingAddress' : string,
  'phone' : string,
}
export interface Lead {
  'name' : string,
  'email' : string,
  'language' : string,
  'company' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Order {
  'id' : bigint,
  'customerInfo' : CustomerInfo,
  'status' : OrderStatus,
  'customerPrincipal' : Principal,
  'totalCents' : bigint,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
  'stripeSessionId' : string,
}
export interface OrderItem {
  'sku' : string,
  'name' : string,
  'quantity' : bigint,
  'priceCents' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface ProductCatalogEntry {
  'sku' : string,
  'nameEn' : string,
  'nameFr' : string,
  'descriptionEn' : string,
  'descriptionFr' : string,
  'stock' : bigint,
  'category' : ProductCategory,
  'priceCents' : bigint,
}
export type ProductCategory = { 'accessory' : null } |
  { 'roll' : null } |
  { 'sheet' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrEditCatalogEntry' : ActorMethod<[ProductCatalogEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCatalogEntry' : ActorMethod<[string], undefined>,
  'flushLeads' : ActorMethod<[], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], ProductCatalogEntry>,
  'getProductCatalog' : ActorMethod<[], Array<ProductCatalogEntry>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setStripeConfigurationWithPassword' : ActorMethod<[string, StripeConfiguration], boolean>,
  'submitLead' : ActorMethod<[Lead], undefined>,
  'submitOrder' : ActorMethod<[Order], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateOrderStripeSessionId' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];